### ISSUE TITLE
Incorrect values in COVID-19 Malta - Vaccination Data.csv

### ISSUE THREAD

**Issue by shaunaxisa** [COVID19-Malta/COVID19-Data#16]
**Python code:**
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/COVID19-Malta/COVID19-Data/master/COVID-19%20Malta%20-%20Vaccination%20Data.csv')
df.iloc[378]
**Output:**
﻿Date of Vaccination                    30/01/2022
Total Vaccination Doses                    1210946
Fully vaccinated (2 of 2 or 1 of 1)       464023.0
Received one dose (1 of 2 or 1 of 1)      450420.0
Total Booster doses                       329806.0
Name: 378, dtype: object
**Remark:**
You exchanged [Fully vaccinated (2 of 2 or 1 of 1)]  with [Received one dose (1 of 2 or 1 of 1)] for 30/01/2022.

**Comment by agiuh001** [comment]
Thanks for noticing. Corrected the swapped values. Sorry for the delay but didn't receive notice of the issue.
