### ISSUE TITLE
incorrectly inputted date

### ISSUE THREAD

**Issue by fenjas** [COVID19-Malta/COVID19-Data#18]
14,04,2022,1237,1408095,1367,442268,2779,1850363

Date has been inputted as 14,04,2022 instead of 14/04/2022. Anything reading the csv will parse it as having 2 extra fields.

Using your data here -> https://fenej72.pythonanywhere.com/

**Comment by ijtan** [comment]
Moreover, the aggregate data has the wrong month as 14/03/2022 instead of /04 as it should be

**Comment by fenjas** [comment]
More than welcome!
